### ISSUE TITLE
adopt open almende/vis network pull requests

### ISSUE THREAD

**Issue by micahstubbs** [visjs-community/visjs-network#27]
adopt open almende/vis network pull requests

review this PRs and work with authors to improve them so that we can merge them here in `visjs-network`

https://github.com/almende/vis/pulls?q=is%3Aopen+is%3Apr+label%3ANetwork

- [ ] almende/vis#4080 requested example, steps to test
- [x] almende/vis#4070 in
- [ ] almende/vis#4044 requested example, steps to test
- [x] almende/vis#4042 in
- [ ] almende/vis#4027 cannot repro underlying bug
- [x] almende/vis#4026 in
- [ ] almende/vis#3991 requested example, steps to test
- [ ] almende/vis#3975 requested example, steps to test
- [ ] almende/vis#3965 requested example, steps to test
- [ ] almende/vis#3963 in
- [ ] almende/vis#3891 PR includes changes from other branch, author will update PR to show only new changes. author to provide example.
- [ ] almende/vis#3888 in
- [ ] almende/vis#3881 requested example, steps to test. open questions from earlier review.
- [ ] almende/vis#3880 requested example, steps to test. open questions from earlier review.
- [ ] almende/vis#3856 failing Travis CI, but has approval from a maintainer
- [ ] almende/vis#3846 requested example, steps to test
- [ ] almende/vis#3771 has example, ready to review
